# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Client check
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/EnglishMasterWebAssembly/Client" # Location of package manifests
    schedule:
      interval: "weekly"
      
  # Server check
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/EnglishMasterWebAssembly/Server" # Location of package manifests
    schedule:
      interval: "weekly"
      
  # Shared check
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/EnglishMasterWebAssembly/Shared" # Location of package manifests
    schedule:
      interval: "weekly"
